---
name: GD-Sparkline
version: 0.05
author:
  - 'Roger M Pettett <rpettett@cpan.org>'
abstract: 'GD::Sparkline - basic sparkline graphs'
license: perl
resources:
  license: http://dev.perl.org/licenses/
build_requires:
  IO::Scalar: 2.110
  Test::More: 0
requires:
  Carp: 1.08
  Class::Accessor: 0.31
  English: 1.04
  GD: 2.41
  Math::Bezier: 0.01
  Readonly: 1.03
  base: 2.13
  strict: 1.04
  warnings: 1.06
configure_requires:
  Module::Build: 0.35
provides:
  GD::Sparkline:
    file: lib/GD/Sparkline.pm
    version: 0.05
generated_by: Module::Build version 0.35
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
