---
name: GD-Sparkline
version: 0.02
author:
  - 'Roger M Pettett <rpettett@cpan.org>'
abstract: 'GD::Sparkline - basic sparkline graphs'
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Carp: 1.08
  Class::Accessor: 0.31
  English: 1.04
  GD: 2.41
  Math::Bezier: 0.01
  Readonly: 1.03
  base: 2.13
  strict: 1.04
  warnings: 1.06
build_requires:
  Test::More: 0
provides:
  GD::Sparkline:
    file: lib/GD/Sparkline.pm
    version: 0.02
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
